[package]
name = "quickcheck_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
tonic = "0.14.1"
serde = { version = "1.0", features = ["derive"] }
quickcheck_rpc = { path = "../quickcheck_rpc" }
rmp-serde = "1.3.0"
